config/routes.rb
Result::Application.routes.draw do
  resources :amounts

  

end

app/models/amount.rb
class Amount < ActiveRecord::Base
end

app/controllers/amounts_controller.rb
class AmountsController < ApplicationController
  before_action :set_amount, only: [:show, :edit, :update, :destroy]

  # GET /amounts
  # GET /amounts.json
  def index
    @amounts = Amount.all
  end



def jisuan
number1 = $one 
number2 = $two 
method = %w(+ - * /)
case method 
when "+"
   $result =  number1 + number2 
when "-"
    $result =  number1 - number2
when "*"
    $result =  number1 * number2
when "/"
    $result =  number1 / number2
end
end

  # GET /amounts/1
  # GET /amounts/1.json
  def show
  end

  # GET /amounts/new
  def new
    @amount = Amount.new
  end

  # GET /amounts/1/edit
  def edit
  end

  # POST /amounts
  # POST /amounts.json
  def create
    @amount = Amount.new(amount_params)

    respond_to do |format|
      if @amount.save
        format.html { redirect_to @amount, notice: 'Amount was successfully created.' }
        format.json { render action: 'show', status: :created, location: @amount }
      else
        format.html { render action: 'new' }
        format.json { render json: @amount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amounts/1
  # PATCH/PUT /amounts/1.json
  def update
    respond_to do |format|
      if @amount.update(amount_params)
        format.html { redirect_to @amount, notice: 'Amount was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @amount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amounts/1
  # DELETE /amounts/1.json
  def destroy
    @amount.destroy
    respond_to do |format|
      format.html { redirect_to amounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amount
      @amount = Amount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amount_params
      params.require(:amount).permit(:one, :two, :result)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/amounts_helper.rb
module AmountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/amounts/_form.html.erb
<%= form_for(@amount) do |f| %>
  <% if @amount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amount.errors.count, "error") %> prohibited this amount from being saved:</h2>

      <ul>
      <% @amount.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :one %>
    <%= f.text_field :one %>
  </div>
  <input method="+" type="radio"  name="1" />+<input method="-" type="radio"  name="1"/>-
  <input method="*" type="radio"  name="1" />*<input method="/" type="radio"  name="1"/>/<br>
 
  <div class="field">
    <%= f.label :two %>
    <%= f.text_field :two %>
  </div>
  <div class="field">
    <%= f.label :result %>
    <%= f.text_field :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amounts/edit.html.erb
<h1>Editing amount</h1>

<%= render 'form' %>

<%= link_to 'Show', @amount %> |
<%= link_to 'Back', amounts_path %>

app/views/amounts/index.html.erb
<h1>Listing amounts</h1>

<table>
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Result</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @amounts.each do |amount| %>
      <tr>
        <td><%= amount.one %></td>
        <td><%= amount.two %></td>
        <td><%= amount.result %></td>
        <td><%= link_to 'Show', amount %></td>
        <td><%= link_to 'Edit', edit_amount_path(amount) %></td>
        <td><%= link_to 'Destroy', amount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amount', new_amount_path %>

app/views/amounts/new.html.erb
<h1>New amount</h1>

<%= render 'form' %>

<%= link_to 'Back', amounts_path %>

app/views/amounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>One:</strong>
  <%= @amount.one %>
</p>

<p>
  <strong>Two:</strong>
  <%= @amount.two %>
</p>

<p>
  <strong>Result:</strong>
  <%= @amount.result %>
</p>

<%= link_to 'Edit', edit_amount_path(@amount) %> |
<%= link_to 'Back', amounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Result</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>